version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/usr/src/app
    command: npm start

  frontend:
    build: ./frontend
    ports:
      - "80:80"
